services:
  ollama:
    image: ollama/ollama:latest
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "ollama serve & sleep 5 && ollama pull deepseek-r1:1.5b && ollama pull llama3.2:3b && wait",
      ]
    environment:
      - OLLAMA_KEEP_ALIVE="24h"
    volumes:
      - ollama-storage:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  webui:
    image: ghcr.io/open-webui/open-webui:latest
    environment:
      - OLLAMA_API_URL="http://ollama:11434"
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>
    volumes:
      - webui-storage:/app/backend/data
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - ollama

  searxng:
    image: searxng/searxng
    ports:
      - "8081:8080"
    volumes:
      - ./searxng:/etc/searxng

volumes:
  ollama-storage:
  webui-storage:
